### ISSUE TITLE
Add a class to currentindex?

### ISSUE THREAD

**Issue by sergioplaza** [ruyadorno/simple-slider#33]
How can I add a class to currentindex? Greetings.

**Comment by rafa-acioly** [comment]
have you tried `onChange: A callback function to be invoked each time a slide changes.`?

**Comment by sergioplaza** [comment]
Hi, I deal with "onChange" but it affects all items and I just want to change the currentindex. Greetings.

**Comment by ruyadorno** [comment]
Hi @sergioplaza I just put together a [new example](https://github.com/ruyadorno/simple-slider/blob/master/examples/add-class-to-current-elem-example.html) using `onChange` but this actually got me thinking that it might be valuable to export a `children()` or `slides()` method to retrieve the children :thinking:

**Comment by sergioplaza** [comment]
Excellent @ruyadorno! This is what I was looking for, thank you very much.
