### ISSUE TITLE
Problem with requestAnimationFrame in Safari

### ISSUE THREAD

**Issue by Agoreddah** [ruyadorno/simple-slider#34]
Some specific versions of Safari (and also some other older browsers) supports requestAnimationFrame only with prefix. In this case, line 216 should be modified to handle these scenarios, f.e.:

```
if (!window.requestAnimationFrame) {
	window.requestAnimationFrame = (function() {
		return 	window.webkitRequestAnimationFrame ||
				window.mozRequestAnimationFrame || 
				window.oRequestAnimationFrame ||
				window.msRequestAnimationFrame ||
				function(callback, element) {
					window.setTimeout(callback, 1000 / 60);
				};
			})();
}

function animate(){
	window.requestAnimationFrame(function (time) {
		if (startTime === 0) {
			startTime = time;
		}
		anim(insertElem, insertFrom, insertTo, removeElem, removeFrom, removeTo, transitionDuration, startTime, time, easeFunc);
	});
}

animate();
```

**Comment by ruyadorno** [comment]
hi @Agoreddah thank you very much for your report 😊 

**simple-slider** used to have a `requestAnimationFrame` polyfill internally in the past but it was [eventually removed](https://github.com/ruyadorno/simple-slider/commit/44d4fc6fa3fc80afcffa98d34b6d0a888e3067c9#diff-9bc6f40d29582e86afa3466e33780193L19) when I started the effort of modernizing the codebase, and there are some logical arguments behind that decision:

- At some point I decided to really switch the focus of the lib towards the small file size and including a polyfill would def bloat the final result
- [The requestAnimationFrame API is quite well supported across browsers these days](https://caniuse.com/#feat=requestanimationframe)
- Separation of concerns, there are many `requestAnimationFrame` polyfills [available out there](https://npms.io/search?q=requestAnimationFrame)

If anyone happen to stumble upon this issue to help with the same issue in the future I would recommend checking out [raf](https://www.npmjs.com/package/raf) which is one of the earliest `requestAnimationFrame` polyfills available and quite easy to use.

Thanks again for bringing the point up and all the best 👍
