### ISSUE TITLE
Multiple Slides At One Time

### ISSUE THREAD

**Issue by ohenepee** [ruyadorno/simple-slider#37]
Is there a way to show multiple sides at a time... say 4 small visible slides that fit horizontally within their container... more like a FIRST-IN-FIRST-OUT style carousel?

**Comment by ruyadorno** [comment]
hi @ohenepee 😊I totally get what you want to achieve but unfortunately **simple-slider** doesn't support multiple sliders 😞 

I considered adding it during the refactor/revamp prior to release [1.0.0](https://github.com/ruyadorno/simple-slider/releases/tag/v1.0.0) but unfortunately supporting that would def increase the final size, seeing that with **simple-slider** I choose to focus on a small file size I decided against adding support for multiple sliders.

I hope you're not too disappointed by the answer but the actual best thing to do is to go with [one of the alternatives](https://github.com/ruyadorno/simple-slider#alternatives) 😅 

All the best 👋
