### ISSUE TITLE
Touch Swipe solving error

### ISSUE THREAD

**Issue by sergioplaza** [ruyadorno/simple-slider#38]
Hello, I was using the [Touch swipe example Guide](http://ruyadorno.github.io/simple-slider/docs/examples/touch-swipe-example-docs.html) and there is an error when trying to scroll down or scroll up. 

**Solution:**

```
(-) var Swipe = new Hammer.Swipe ();
(+) var Swipe = new Hammer.Swipe ({direction: Hammer.DIRECTION_HORIZONTAL});
```

Greetings.

**Comment by ruyadorno** [comment]
thanks for the suggestion 😄
