### ISSUE TITLE
Gaps between Images

### ISSUE THREAD

**Issue by georgmo** [ruyadorno/simple-slider#44]
Hi

I am using a simple slider here:
www.arch-foto.com/splash

The images should merge into each other like they do here:
http://ruyadorno.github.io/simple-slider/docs/examples/fading-transition-docs.html

But what happens is this: image fades out to background - about a second only background color - next image fades in from background color
Only between the last image and the first (when the loop is completed) the slides behave as they should.
Neither "duration", nor "delay" change anything about it.

this is the code, that my developer integrated. it differs from the example-page above in the lines between "<script>" and "prop". Is that the reason? (sorry for my way of writing - i am no developer)
You can also contact me at the email shown on the above website.

![2019-05-07-000545](https://user-images.githubusercontent.com/17085498/57384775-70f89480-71b1-11e9-8a10-2def45baddd9.jpg)

**Comment by ruyadorno** [comment]
Hi Georg, I checked www.arch-foto.com/splash and it does look alright, there could be some display issues when loading since the images are large but overall it looks like working as intended.
